include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    prefer_single_quotes: true
    public_member_api_docs: false

analyzer:
  exclude:
    - "**/*.gem.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"