name: what_color
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  cloud_firestore: ^4.4.5
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.4
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0

  geolocator: ^9.0.2
  google_maps_cluster_manager: ^3.0.0+1
  google_maps_flutter: ^2.2.4
  google_sign_in: ^6.0.2
  intl: ^0.17.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  table_calendar: ^3.0.8
  very_good_analysis: ^4.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
